services:
  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER : ${DB_USER}
      POSTGRES_PASSWORD : ${DB_PASSWORD}
      POSTGRES_DB : ${DB}
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./nextjs
    ports:
      - "${NEXTJS_PORT}:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      CALENDAR_ID: ${CALENDAR_ID}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      GOOGLE_MAP_API_URL: ${GOOGLE_MAP_API_URL}
    depends_on:
      - db
    volumes:
      - ./nextjs:/app
      - nextjs_modules:/app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  db_data:
  nextjs_modules: